#!/usr/bin/env python
experiment_settings =  [
    {
        "model_name": "codebert",
        "model_checkpoint": "microsoft/codebert-base",
        "model_save_dir": "./models/transformer_codebert",
        "learning_rate_clone": 1e-5,
        "batch_size_clone": 2,
        "learning_rate_class": 1e-5,
        "batch_size_class": 2,
    },
    {
        "model_name": "codeberta",
        "model_checkpoint": "huggingface/CodeBERTa-language-id",
        "model_save_dir": "./models/transformer_codeberta",
        "learning_rate_clone": 1e-5,
        "batch_size_clone": 2,
        "learning_rate_class": 1e-5,
        "batch_size_class": 2,
    },
    {
        "model_name": "graphcodebert",
        "model_checkpoint": "microsoft/graphcodebert-base",
        "model_save_dir": "./models/transformer_graphcodebert",
        "learning_rate_clone": 2e-4,
        "batch_size_clone": 2,
        "learning_rate_class": 2e-4,
        "batch_size_class": 2,
    },
    {
        "model_name": "codet5base",
        "model_checkpoint": "Salesforce/codet5-base",
        "model_save_dir": "./models/transformer_codet5base",
        "learning_rate_clone": 2e-4,
        "batch_size_clone": 2,
        "learning_rate_class": 2e-4,
        "batch_size_class": 2,
    },
    {
        "model_name": "codet5p110membedding",
        "model_checkpoint": "Salesforce/codet5p-110m-embedding",
        "model_save_dir": "./models/transformer_codet5p110membedding",
        "learning_rate_clone": 1e-4,
        "batch_size_clone": 2,
        "learning_rate_class": 1e-4,
        "batch_size_class": 2,
    },
    {
        "model_name": "astnn",
        "model_checkpoint": "astnn",
        "model_save_dir": "./models/astnn",
        "learning_rate_clone": 0.002,
        "batch_size_clone": 2,
        "learning_rate_class": 0.002,
        "batch_size_class": 2,
    },
    {
        "model_name": "plbart-java-clone-detection",
        "model_checkpoint": "uclanlp/plbart-java-clone-detection",
        "model_save_dir": "./models/plbart-java-clone-detection",
        "learning_rate_clone": 5e-05,
        "batch_size_clone": 2,
        "learning_rate_class": 5e-05,
        "batch_size_class": 2,
    },
    {
        "model_name": "plbart",
        "model_checkpoint": "uclanlp/plbart-base",
        "model_save_dir": "./models/transformer_plbart",
        "learning_rate_clone": 5e-05,
        "batch_size_clone": 2,
        "learning_rate_class": 5e-05,
        "batch_size_class": 2,
    }
]